application:
# host to allow connections to docker
  host: 0.0.0.0
  port: 8000
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
  require_ssl: true
email_client:
  base_url: "https://api.postmarkapp.com"
  sender_email: "test@gmail.com"
  authorization_token: "my-secret-token"
  timeout_ms: 10000